# PHP
phpfpm:
  build: .
  restart: always
  links:
    - db:db
  volumes:
    - ./app:/var/www/html
# NGINX
nginx:
  restart: always
  image: nginx
  ports:
    - "99:80"
  links:
    - phpfpm:phpfpm
  volumes:
    - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./app:/var/www/html
    - ./log/nginx:/var/log/nginx
# MYSQL
db:
  restart: always
  image: mysql
#  ports:
#   - "3320:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: user
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: database